### ISSUE TITLE
Questions and suggestions about firmware

### ISSUE THREAD

**Issue by LOVECHEN** [dr-mark-roberts/open-dyson-battery#3]
Excuse me, can this be directly flashed into the native v8 battery motherboard? I have compiled
Can you add temperature monitoring (internal thermistor)
thank you very much

**Comment by dr-mark-roberts** [comment]
Hi. 
Yes it can be directly flashed into V8 board. For V8 `-DHW_V8_180207` should be enabled in the Makefile.
`180207` is the marking on the board. I tried it only with this version of the board.
Unfortunately I don't have much time right now to work on this project. 
If anyone provides a PR I would be glad to merge it.
Thank you for the interest in this project.

**Comment by LOVECHEN** [comment]
thank you doctor

**Comment by TonyJOE598** [comment]
> thank you doctor@LOVECHEN

Hello, could you please send me a copy of the v6 and v8hex files? I don't understand anything about them. Thank you very much. MctiernanMoncivais282@gmail.com
